# Generated by Django 4.1.13 on 2025-02-12 13:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_delete_loginas_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0018_fidus_3_4'),
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConftoolAccessRight',
            fields=[
                ('accessright_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.accessright')),
            ],
            bases=('document.accessright',),
        ),
        migrations.CreateModel(
            name='ConftoolDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document.document')),
                ('conftool_id', models.PositiveBigIntegerField(unique=True)),
                ('synchronized', models.DateTimeField()),
            ],
            bases=('document.document',),
        ),
        migrations.CreateModel(
            name='ConftoolEmail',
            fields=[
                ('emailaddress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.emailaddress')),
            ],
            bases=('account.emailaddress',),
        ),
        migrations.CreateModel(
            name='ConftoolUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('conftool_id', models.PositiveBigIntegerField(unique=True)),
                ('synchronized', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConftoolUserInvite',
            fields=[
                ('userinvite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userinvite')),
            ],
            bases=('user.userinvite',),
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=8)),
                ('path', models.CharField(db_index=True, max_length=80)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error_type', models.CharField(blank=True, choices=[('FL', 'Fetch Login'), ('FU', 'Fetch Userdata'), ('EU', 'Export User'), ('EP', 'Export Papers'), ('IU', 'Import Userdata'), ('IE', 'Import User Emails'), ('IP', 'Import Paper')], max_length=2)),
                ('message', models.TextField(blank=True, db_index=True, null=True)),
                ('conftool_paper_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stacktrace', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
