# Generated by Django 4.1.13 on 2025-02-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhdconf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="path",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="importlog",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
    ]
