# Generated by Django 5.2.9 on 2026-08-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dhdconf", "0001_initial"),
        ('dhdconf', '0002_alter_importlog_path_alter_importlog_request_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConftoolAccessRight',
        ),
        migrations.DeleteModel(
            name='ConftoolEmail',
        ),
        migrations.DeleteModel(
            name='ConftoolUserInvite',
        ),
    ]
